global: 
 scrape_interval: 5s 
 external_labels: 
   monitor: 'my-monitor'
   origin_prometheus: prometheus
rule_files: 
 - 'alert.rules' 
scrape_configs: 
 - job_name: 'prometheus' 
   basic_auth: 
      username: promUSERNAME  # add here your Username of the prometheus authentication login 
      password: promPASSWORD  # add here your Password of the prometheus authentication login 
   static_configs: 
     - targets: ['localhost:9090'] 
   scheme: https 
   tls_config: 
     ca_file: /tls/prometheus.crt 
 - job_name: 'node-exporter' 
   basic_auth: 
      username: nodeUSERNAME  # add here your Username of the node-exporter authentication login
      password: nodePASSWORD  # add here your pw of the node-exporter authentication login 
   static_configs: 
     - targets: ['node_exporter:9100']  # add the container ID of your running node-exporter 
   scheme: https 
   tls_config:
     ca_file: /tls/prometheus.crt 
     cert_file: /tls/prometheus.crt 
     key_file: /tls/prometheus.key 
     insecure_skip_verify: true 
 - job_name: 'DOCKER-TARGET' 
   static_configs: 
     - targets: ['CONTAINER-ID:PORT-NUMBER']  # add the container ID of your target and if you use a diffrent port you can also configure it 
   scheme: https 
   tls_config: 
     insecure_skip_verify: true 
remote_write: 
 - url: Grafana-Supplied-URL
   basic_auth: 
      username: Your-User-Name 
      password: Your-Api-PW
